### ISSUE TITLE
command 'extension.multiCommand.execute' not found

### ISSUE THREAD

**Issue by XPYY7** [ryuta46/vscode-multi-command#82]
I downloaded the file and copied it to the C:\Users\a\.vscode\extensions folder. I can see that the plugin is installed on the VSCode extension page.
When I press F1, VSCODE prompts：command'extension.multiCommand.execute' not found
The path to my keybindings.json is C/users/a/AppData/Roaming/VSCode/user/keybindings.json
The path to my settings.json is:
C/users/a/AppData/Roaming/VSCode/user/setting.json
Look for the answer.
I would love to be able to use this extension

**Comment by schuylermaclay** [comment]
@XPYY7 I had the same issue on mac with cursor and vscode, what worked for me:

- Uninstalled multi-command
- wiped references in keybindsings.json and settings.json
- rm'd the directory in  ~/.vscode/extensions
- reinstalled multi-comand and added commands back
- I rewrote/used new commands, so its possible that some of my commands were wrong, but they hadn't been changed in a very long time and I tried simplifying removing them as a first step


Anyway, thanks for the fast reply and the excellent extension!

**Comment by dustinlacewell** [comment]
I'm still getting this issue.

[Window Title]
Cursor

[Main Instruction]
Command 'Multi command: Execute multi command' resulted in an error

[Content]
command 'extension.multiCommand.execute' not found

[OK]

**Comment by dustinlacewell** [comment]
```
2025-04-08 01:02:07.539 [error] Activating extension ryuta46.multi-command failed due to an error:
2025-04-08 01:02:07.539 [error] TypeError: Cannot read properties of undefined (reading 'map')
	at createMultiCommand .cursor\extensions\ryuta46.multi-command-1.6.0\out\extension.js:56:40)
	at .cursor\extensions\ryuta46.multi-command-1.6.0\out\extension.js:83:30
	at Map.forEach (<anonymous>)
	at refreshUserCommands (.cursor\extensions\ryuta46.multi-command-1.6.0\out\extension.js:82:14)
	at activate (.cursor\extensions\ryuta46.multi-command-1.6.0\out\extension.js:93:5)
```

**Comment by sim0wastaken** [comment]
In my .code-workspace I did this

```
{
  "folders": [{ "path": "." }],
  "settings": {
    "multiCommand.commands": [
      {
        "command": "multiCommand.runAllServices",
        "sequence": [
          "workbench.action.tasks.runTask Run Central Server",
          "workbench.action.tasks.runTask Run Chat Service",
          "workbench.action.tasks.runTask Run Mongodb Service",
          "workbench.action.tasks.runTask Run Postgres Service",
          "workbench.action.tasks.runTask Run Frontend"
        ]
      }
    ]
  }
}
```
